import GlobalStyle from './../src/theme/GlobalStyle.js'
import { Open_Sans } from 'next/font/google';
export const metadata = {
  title: 'Alura Cases',
  description: 'Generated by Next.js',
}

const mainFontFamily = Open_Sans({
  weight: ['300', '400', '700', '800'],
  subsets: ['latin'],
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className={mainFontFamily.className}>
      <GlobalStyle />
      <body>{children}</body>
    </html>
  )
}
