import GlobalStyle from './../src/theme/GlobalStyle.js'
export const metadata = {
  title: 'Alura Cases',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <GlobalStyle />
      <body>{children}</body>
    </html>
  )
}
